### ISSUE TITLE
Removing IPv4-only DNS Servers

### ISSUE THREAD

**Issue by kkarhan** [greyhat-academy/lists.d#15]
I'd propose we remove IPv4-only DNS-Servers as Dual-Stack, CGNAT and IPv6-only connectivity is becoming more and more mainstream.

See the following commit:
https://github.com/greyhat-academy/lists.d/commit/5e3f8b94bc093ab5455b9b31a6dc2736a59ab4da

Please let me your opinions  - espechally if you have serious objections against that.

**Comment by x86pup** [comment]
Don't have any objections to doing it, but there are still a fair amount of mainstream ISPs who fail to provide IPv6 connectivity or proper connectivity (no 6to4) in the US such as Frontier Communications (no workaround, can't even configure 6to4 to use something like HE Tunnel Broker, and I use them), Cox Communications Internet (apparently only works if your router supports tunneling/6to4), and people report flakey results or no IPv6 with Starlink.

The current list of IPv4-only DNS servers are very niche providers which is the only reason why I'm not objecting to removing IPv4-only servers.

**Comment by kkarhan** [comment]
Thanks for your input, @r3g-5z and sorry for my delayed reply.

As of now there are [only 4 entries](https://github.com/greyhat-academy/lists.d/blob/main/dns.servers.list.tsv) in the entire list.

All other DNS Servers are dual-stack.

In terms of [NTP Servers](https://github.com/greyhat-academy/lists.d/blob/main/ntp.servers.list.tsv) it seems a bit more flaky, but then again these should usually be resolved via DNS, not IP, espechally since some may be pools using round-robin configuration and CDN methods like anycast to find the (network-logically) closest server, but that's a different issue...

Personally, I also suffer from IPv4-only connectivity [a /29 subnet, but still not even a single /64 prefix], so Dual-Stack is a necessity for me.

**Comment by kkarhan** [comment]
I've removed all IPv4-only DNS-Servers [4 entries in total].
All other entries are Dual-Stack [IPv4 & IPv6]...
