### ISSUE TITLE
unrelated - status update

### ISSUE THREAD

**Issue by kkarhan** [greyhat-academy/lists.d#16]
Hi, I just want to inform you [why my Twitter is down](https://github.com/kkarhan/misc-stuff/blob/main/publications/statements/20221102/hey-twitter.md).

Not shure how much it's linked to this project as previous mass false reportings against me failed.

Tho with a locked-down account I can't DM you.

**Comment by x86pup** [comment]
Do you have a Mastodon account?

**Comment by kkarhan** [comment]
Yeah, but sadly the instance I used went belly-up...
https://mastodon.starrevolution.org/@k3vk4

**Comment by kkarhan** [comment]
still reachable via Keybase tho: https://keybase.io/kkarhan/

**Comment by OstDeutschAntiFa** [comment]
Hör auf, dich wie die Faschisten zu benehmen. Hören Sie auf, schwarze, braune und Transgender-Personen zu belästigen.

Ich hoffe, Sie haben Ihre Lektion gelernt.

Hören Sie auf, "fash" Angriffe in Deutschland offen zu planen.

**Comment by OstDeutschAntiFa** [comment]
Translation in English:

Stop acting like the fascists. Stop harassing black, brown, and transgender people.

Hope you have learned your lesson.

Stop openly plotting "fash" attacks in Germany.

**Comment by OstDeutschAntiFa** [comment]
PR https://github.com/kkarhan/misc-stuff/pull/1

**Comment by kkarhan** [comment]
Obviously, @OstDeutschAntiFa is an account solely setup to harrass me, as it's github activity shows.
https://github.com/OstDeutschAntiFa

This thread will be locked & appropriate actions will be taken.

**Comment by kkarhan** [comment]
TTYL
https://github.com/kkarhan/misc-stuff/blob/main/publications/statements/20221110/serial-harassers.md

**Comment by kkarhan** [comment]
closing issue
https://twitter.com/k3vk4
