### ISSUE TITLE
add kitsunes.gay and kitsunes.club TOR links 

### ISSUE THREAD

**Issue by JosephArney566** [greyhat-academy/lists.d#24]
**kitsunes.club:** 
http://kitclbnacd7amkjjxy47eysdfirnqpni2wauric6ycbjli6v3xw5vdyd.onion/
**kitsunes.gay:**
http://kitgayhfl4kedfoju4dhjwhysxrfxt4jvaze5bqyux6uztaidjuk3syd.onion/

**Comment by kkarhan** [comment]
@JosephArney566 thanks for the submission.

Please link to posts by the admin account or website of said calckey instances that proove said onions in a readable form.
Similar to other entries in https://github.com/greyhat-academy/lists.d/blob/main/onion.domains.list.tsv

**Comment by kkarhan** [comment]
The issue will remain open until feedback by original reporter is given.

**Comment by Kio-td** [comment]
Afternoon, @kkarhan!
I'm Kio! (https://kitsunes.club/notes/9id59raayqlj06c4)

KitsuClub is using kitclu5euns4jdutq2fuusbuqj2bjrwglyxmnvzvwga7wiovbfuoqaqd.onion
KitsuGay is using kitgayb6n6klaytma4feoblj3akwjpf727cv4hxcs5v3gpwwirsxfvyd.onion

Proof of ownership- Well, there's a post there now, and also through explicit Onion-location Headers.

**Comment by kkarhan** [comment]
@Kio-td  I fixed it.

See: [commit](https://github.com/greyhat-academy/lists.d/commit/c04d7708bdc5293151581776bad81d61b01768d5)

Thx for your patience.
