### ISSUE TITLE
add horny.house

### ISSUE THREAD

**Issue by GoddessZenith** [greyhat-academy/lists.d#28]
URL:
[https://horny.house/](https://horny.house/)

Reason:
[https://tech.lgbt/@Zenith/110475616879703323](https://tech.lgbt/@Zenith/110475616879703323)

Post archive:
Hello, I am posting on behalf of the System of Goddess Zenith. This is in regards to horny.house:

For those that don't know I had an account there as my Facet of Depravity which was one of my Sex Working accounts.

On the site I was given the ability to moderate. I had been away from doing so for a while due to personal matters (with being unnhomed due to police violence, then having to move cross country, it has been a lot...), and while no time has ever been a good time for me to moderate for me, I eventually found time.

Yesterday at about midnight, 6/2/2023 EST I returned to moderating. Many reports were found leveraged against one user named LL. I agreed with user reports on the fundamentals of the matter and suspended the account.

At 11:33 AM EST I received a DM from the admin that they reversed my decision because they saw nothing wrong, but they suspended a domain (shota.house).

In that, I have decided to step down from horny.house.
Additionally, regarding the content reported:

LL was (and likely still is) posting loli/shota pornography and stories relating to characters who are students in sexual situations. 

Additional information:
horny.house does not, as of the time of this posting, have a clear set of standards or rules in which to administrate. Given the server is for Sex Workers and pornography, this does not sit well for me.

Additionally, now at this time the server has about 350 active users, and only one relatively inactive admin.

Given all evidence, my experience in Sex Work, as a person, and the situation, I have every reason to believe that horny.house is not a safe place in which to federate with. And should be defederated.
[#fediblock](https://tech.lgbt/tags/fediblock)

**Comment by kkarhan** [comment]
Thanks for this report of yours.

Said Domain has been added to the list with the latest commit:
https://github.com/greyhat-academy/lists.d/blob/d4522313bb287f1acda3f344fdef98005ad5ca25/activitypub.domains.block.list.tsv#L31

I really appreciate your contribution.

**Comment by kkarhan** [comment]
Thanks for this report of yours.

Said Domain has been added to the list with the latest commit:
https://github.com/greyhat-academy/lists.d/blob/d4522313bb287f1acda3f344fdef98005ad5ca25/activitypub.domains.block.list.tsv#L31

I really appreciate your contribution.

**Comment by kkarhan** [comment]
The entry has been removed in accordinance based off [another issue](https://github.com/greyhat-academy/lists.d/issues/36) 

Please feel free to comment on that issue if you want to contest that change.

**Comment by kkarhan** [comment]
@GoddessZenith Please provide at least 1 source for said accusation so I'll revert the changes...
https://tech.lgbt/@Zenith/110601782813900938

**Comment by kkarhan** [comment]
As per your report, shota.house was added.
See https://github.com/greyhat-academy/lists.d/commit/a9e9a685d21e340107635daaaf5c5a3f1f70f2b2 ...

@GoddessZenith Since you haven't provided any feedback I'll close this issue.
Feel free to reopen it with additional feedback.
