### ISSUE TITLE
Reported for CSAM

### ISSUE THREAD

**Issue by RoxyBoxxy** [greyhat-academy/lists.d#36]
Ref: https://github.com/greyhat-academy/lists.d/blob/7c77ff33b04762210a9780660caa0fb856d8ea7d/activitypub.domains.block.list.tsv#L38

Hi i am the owner of horny.house and no CSAM has been posted what so ever, maybe images the could be questionable but are of the ages 18+, anything borderline is reviewed and action is taken if necessary, i do not condone anybody posting CSAM material on ANY platform. The reason the user was unbanned so as warning could be issued saying that the content was borderline and people could take it as a CSAM post, i removed the post and the image, this was the only event from this user so a perma ban was not warranted in this specific case

Thanks 

Rox

**Comment by kkarhan** [comment]
Hi @RoxyBoxxy,  
thanks for filing the report.

I've unlisted it as requested, but will undo the change if evidence is being provided that indicate otherwise.

**Comment by RoxyBoxxy** [comment]
> Hi @RoxyBoxxy, thanks for filing the report.
> 
> I've unlisted it as requested, but will undo the change if evidence is being provided that indicate otherwise.

If there is any evidence feel free to send it my way so i can take action as from the reports i could not see anything over the line, how ever the Ex moderator could of removed said content and i was just unable to see it

Thanks

**Comment by kkarhan** [comment]
Shure.

Also thanks for [your transparency](https://estrogen.plus/notes/9ge7gjd2o34znf0u) on the matter, including the [reports you recieved](https://gist.github.com/RoxyBoxxy/9d3d8b98901f51f5fc0f4604cf30a19b).

I do appreciate the openness and transparency and will OFC see this as a two-way road.

I consider the matter resolved at this point unless there's anything needed further down the line.

**Comment by kkarhan** [comment]
The [original issue](https://github.com/greyhat-academy/lists.d/issues/28) has been closed and referenced to this one with request for comment by the original issue creator, @GoddessZenith ,

**Comment by RoxyBoxxy** [comment]
Adding in my proof to this issue

https://gist.github.com/RoxyBoxxy/9d3d8b98901f51f5fc0f4604cf30a19b

JSON of all the reports

the only thing about CSAM is LL reporting CSAM from a diffrent fedi [Here](https://gist.github.com/RoxyBoxxy/9d3d8b98901f51f5fc0f4604cf30a19b#file-reports-json-L896)

**Comment by kkarhan** [comment]
Awaiting Resolution [as per comment](https://github.com/greyhat-academy/lists.d/issues/28#issuecomment-1605851003)... 

[Original Issue](https://github.com/greyhat-academy/lists.d/issues/28) has been reopened and awaiting evidence.

**Comment by kkarhan** [comment]
Since I didn't get any feedback by the original poster, I'll close this issue as done.
