### ISSUE TITLE
[Request]: Additional ActivityPub Blocks

### ISSUE THREAD

**Issue by lexi-the-cute** [greyhat-academy/lists.d#37]
federated.fun, decayable.ink, blob.cat, apogee.polaris-1.work, the.usualsuspects.lol, rot.gives, and crlf.ninja.

See https://alexisart.me/@alexis/110697327210384140, https://alexisart.me/@alexis/110697475533884861, https://alexisart.me/@alexis/110697523244752456, and https://alexisart.me/@alexis/110697612182330507

As per request at https://alexisart.me/@kkarhan@mstdn.social/110697488377123769

**Comment by IcedQuinn** [comment]
The post I'm quoted in is sarcasm. The words that are claimed to be objectionable are surrounded in quote markers and followed by "iced quinn has SIGSEGV," where sigsegv is a well known Unix command code for crashing.

Blob.cat does in fact moderate openly anti-trans content (such as the other posts linked here, which say some rather direct and nasty things to alexis.)

**Comment by kkarhan** [comment]
hi @alexisart, thx for submitting these...
Sorry for my late reply---

Mind if I keep [blob.cat](https://blob.cat) out of this since they [seem to be working on that](https://blob.cat/objects/cd4e14da-6c60-47fc-a1e8-2d67f5a1f313 ) according to [an admin](https://blob.cat/users/Jain) [of blob.cat](https://blob.cat/about)?

**Comment by kkarhan** [comment]
The following domains [have been added](https://github.com/greyhat-academy/lists.d/commit/3e0ec7e6e68a992ba9eb26da03c6b20141e44d56):
```
federated.fun
decayable.ink
apogee.polaris-1.work
rot.gives
the.usualsuspects.lol
crlf.ninja
```

**Comment by lexi-the-cute** [comment]
> hi @alexisart, thx for submitting these...
> Sorry for my late reply---
> 
> Mind if I keep [blob.cat](https://blob.cat) out of this since they [seem to be working on that](https://blob.cat/objects/cd4e14da-6c60-47fc-a1e8-2d67f5a1f313 ) according to [an admin](https://blob.cat/users/Jain) [of blob.cat](https://blob.cat/about)?
> 

sure

**Comment by JainWasUsed** [comment]
Here are the results of the research: https://blob.cat/notice/AXbAn0v5rmzBUc65Pk
It basically says the same what @IcedQuinn wrote above.
Here is the acknowledgement of @lexi-the-cute https://nya.house/notice/AXc6pBRE78zOdKPSUq or https://alexisart.me/@alexis/110700360903757991
I dont want to quote eris when i asked her about the thread of critical. The instance & posts from disqordia no longer exists and signs of transphobia are not present there either

**Comment by kkarhan** [comment]
Thx Everyone... 

Unless there's something else I'd close this as resolved.

@IcedQuinn @lexi-the-cute @JainWasUsed feel free to reopen this if need be.
