### ISSUE TITLE
Block Skinheads.social

### ISSUE THREAD

**Issue by Happyfeet01** [greyhat-academy/lists.d#41]
This platform is for right-wing extremists and neo-Nazis who post their garbage there. You report instance or accounts makes no sense. Therefore block.

**Comment by kkarhan** [comment]
@Happyfeet01 thx for your submission.

Said domain has been added to [activitypub.domains.block.list.tsv](https://github.com/greyhat-academy/lists.d/blob/main/activitypub.domains.block.list.tsv) as per [this commit](https://github.com/greyhat-academy/lists.d/commit/4ad58b67bc7272e45dd2519e1c27840f56a9b689).

Thanks and please feel free to open up a new issue for other domains - you can even includie multiple ones in a submission.
Feel free to add some detailed data / screenshots of evidence if the main site isn't a straight give-away of said content [unless that would be illegal!]... 

Unless there's anything you need to add I'll close this issue as completed.
- Kev
