### ISSUE TITLE
Adding h-i.social to activitypub.domains.block.list.tsv

### ISSUE THREAD

**Issue by kromonos** [greyhat-academy/lists.d#49]
Because `h-i.social` is the new instance from the `ubiqueros.com` owner: https://h-i.social/@are0h

https://github.com/greyhat-academy/lists.d/blob/5bc934053aa0505f172e9c277851b4960d28fddb/activitypub.domains.block.list.tsv#L11C1-L11C14

**Comment by kkarhan** [comment]
Thanks for the info & sorry for my late reply.

Said domain has been added to [``activitypub.domains.block.list.tsv``](https://github.com/greyhat-academy/lists.d/blob/main/activitypub.domains.block.list.tsv) as per [this commit](https://github.com/greyhat-academy/lists.d/commit/a3ec2d17f27276eab7c545c38d305d64d401115e).
