### ISSUE TITLE
one more domain for kromonos

### ISSUE THREAD

**Issue by thealexparadox** [greyhat-academy/lists.d#54]
he used to have an instance on tavern.drow.be (in fact, it's still searchable) though it's been gone for ages.

drow.be also belongs to him and here's the proof.
![84603fee1e3af5db](https://github.com/greyhat-academy/lists.d/assets/21365310/198a2e19-218f-4cf7-9d72-b40bc5099e66)

**Comment by kkarhan** [comment]
thx will be added asap

**Comment by kkarhan** [comment]
done
