### ISSUE TITLE
Portscanners

### ISSUE THREAD

**Issue by fuomag9** [greyhat-academy/lists.d#57]
As per https://lime.fuo.fi/notes/9t8hbz3zcw9zbbek, 104.28.154.164 seems to be doing port scanning and it's owned by cloudflare

**Comment by kkarhan** [comment]
Thanks, I'll also add those as per [source](https://mk.absturztau.be/notes/9tecg794q2df009y)...

```
35.203.210.0/23
104.28.154.0/24
162.216.149.0/24
162.216.150.0/24
198.235.24.0/24
205.210.31.0/24
```

**Comment by kkarhan** [comment]
Added.
Feel free to open a new ticket for different IP blocks.
