### ISSUE TITLE
Remove awakari.com

### ISSUE THREAD

**Issue by akurilov** [greyhat-academy/lists.d#61]
Remove entry: https://github.com/greyhat-academy/lists.d/blob/77e61b055ad5eb2de6f943a3ab31711bfb5463ab/activitypub.domains.block.list.tsv#L10

Added with: https://github.com/greyhat-academy/lists.d/pull/58

False claims.
Awakari doesn't offer any paid service, it's open source and free to use: https://github.com/awakari
Respects #nobot, robots.txt, manual follow request approval etc: https://github.com/awakari/.github/blob/master/OPT-OUT.md
Receives a content just like any other Fediverse software via Activitypub protocol.

See also other's feedback on the issue: https://mastodon.africa/@GrahamDowns/112902922790317417

**Comment by kkarhan** [comment]
Sorry for my very late reply...

1. [The post cited is 404](https://mastodon.africa/@GrahamDowns/112902922790317417).
2. The  [original cause for listing - being a scraper]( https://github.com/greyhat-academy/lists.d/blob/e875ac8e90171a9cec80961a92e9d3cadecacae6/activitypub.domains.block.list.tsv#L6 ) is still valid and correct. 
3. It's a matter of consent to *not use opt-out, but explicit opt-in*! Something you [didn't understood AFAICS]( https://github.com/greyhat-academy/lists.d/issues/61#issue-2471956171 ).

Please fix  2. & 3. and I'll reconsider this issue and PR.
- I'll reconsider once that's done . Please open a new issue and cite this and the PR and provide evidence that said reason for the listing doesn't apply anymore.
